version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  apache:
    image: httpd
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/usr/local/apache2/htdocs/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxynetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.www-phpfpm.rule=Host(`phpfpm.lxc`, `www.phpfpm.lxc`)"
        - "traefik.http.middlewares.wwwredirectregex.redirectregex.regex=^http://phpfpm.lxc/(.*)"
        - "traefik.http.middlewares.wwwredirectregex.redirectregex.replacement=http://www.phpfpm.lxc/$${1}"
        - "traefik.http.routers.www-phpfpm.entrypoints=web"
        - "traefik.http.services.www-phpfpm.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:latest
    volumes:
      - ${PWD}/apps:/usr/local/apache2/htdocs
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
