version: "3.4"
networks:
  proxylampy:
    external: true
  net:
    driver: overlay
    attachable: true

volumes:
  mariadb_data:
services:
  phpfpmexec:
    image: koromerzhin/phpfpm:7.4.12
    command: sh -c "composer install"
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  apache:
    image: httpd:2.4.48
    depends_on:
      - phpfpm
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.phpfpm.rule=HostRegexp(`phpfpm.traefik.me`, `phpfpm.{ip:.*}.traefik.me`)"
        - "traefik.http.services.phpfpm.loadbalancer.server.port=80"
  phpfpm:
    image: koromerzhin/phpfpm:7.4.12-xdebug
    volumes:
      - ${PWD}/apps:/var/www/
      - ${PWD}/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - net
    depends_on:
      - mariadb
      - mailhog
    deploy:
      labels:
        - "traefik.enable=false"
